package org.tsicoop.sign.service.v1;

import org.tsicoop.sign.framework.PoolDB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class DocumentRepository {

    public record DocumentRecord(
            String documentId,
            String appId,
            String templateId,
            String title,
            String storageProviderId,
            String originalStorageKey,
            String originalHash,
            String sealedStorageKey,
            String sealedHash,
            String status
    ) {
    }

    public record DocumentSummary(
            String documentId, String title, String templateName, String status, String createdAt
    ) {
    }

    public record SealSummary(
            String sealId, String providerId, String keyAlias, String signatureStandard, String sealedAt
    ) {
    }

    /**
     * documentId is generated by the caller (not left to the DB's default)
     * because the storage key (§5) is derived from it before the row is
     * ever written — the PDF must land at a path containing the same id
     * that ends up in documents.document_id.
     */
    public void createDraftWithId(String documentId, String appId, String templateId, String title,
                                   String storageProviderId, String originalStorageKey, String originalHash)
            throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("INSERT INTO documents " +
                    "(document_id, app_id, template_id, title, storage_provider_id, original_storage_key, original_hash, status) " +
                    "VALUES (?::uuid, ?::uuid, ?::uuid, ?, ?, ?, ?, 'DRAFT')");
            ps.setString(1, documentId);
            ps.setString(2, appId);
            ps.setString(3, templateId);
            ps.setString(4, title);
            ps.setString(5, storageProviderId);
            ps.setString(6, originalStorageKey);
            ps.setString(7, originalHash);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /** Scoped to appId so one App can never seal/read another's document (§8). */
    public Optional<DocumentRecord> findByIdForApp(String appId, String documentId) {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = null;
        try {
            pool = new PoolDB();
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT document_id, app_id, template_id, title, storage_provider_id, " +
                    "original_storage_key, original_hash, sealed_storage_key, sealed_hash, status " +
                    "FROM documents WHERE document_id = ?::uuid AND app_id = ?::uuid");
            ps.setString(1, documentId);
            ps.setString(2, appId);
            rs = ps.executeQuery();
            if (rs.next()) {
                return Optional.of(new DocumentRecord(
                        rs.getString("document_id"),
                        rs.getString("app_id"),
                        rs.getString("template_id"),
                        rs.getString("title"),
                        rs.getString("storage_provider_id"),
                        rs.getString("original_storage_key"),
                        rs.getString("original_hash"),
                        rs.getString("sealed_storage_key"),
                        rs.getString("sealed_hash"),
                        rs.getString("status")));
            }
            return Optional.empty();
        } catch (Exception e) {
            return Optional.empty();
        } finally {
            if (pool != null) pool.cleanup(rs, ps, con);
        }
    }

    public void markSealed(String documentId, String sealedStorageKey, String sealedHash) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET sealed_storage_key = ?, sealed_hash = ?, " +
                    "status = 'SIGNED', updated_at = now() WHERE document_id = ?::uuid");
            ps.setString(1, sealedStorageKey);
            ps.setString(2, sealedHash);
            ps.setString(3, documentId);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    public void insertSeal(String documentId, String signerId, String providerId, String keyAlias,
                            String transactionId, String pkcs7Signature, String signatureStandard,
                            String caIssuer, String authType) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("INSERT INTO document_seals " +
                    "(document_id, signer_id, provider_id, key_alias, transaction_id, pkcs7_signature, " +
                    "signature_standard, ca_issuer, auth_type) " +
                    "VALUES (?::uuid, ?::uuid, ?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, documentId);
            ps.setString(2, signerId);
            ps.setString(3, providerId);
            ps.setString(4, keyAlias);
            ps.setString(5, transactionId);
            ps.setString(6, pkcs7Signature);
            ps.setString(7, signatureStandard);
            ps.setString(8, caIssuer);
            ps.setString(9, authType);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /** §10.4 Documents & Audit Trail list, scoped to one App. */
    public List<DocumentSummary> listForApp(String appId) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT d.document_id, d.title, t.template_name, d.status, " +
                    "d.created_at::text AS created_at FROM documents d " +
                    "LEFT JOIN templates t ON t.template_id = d.template_id " +
                    "WHERE d.app_id = ?::uuid ORDER BY d.created_at DESC");
            ps.setString(1, appId);
            rs = ps.executeQuery();
            List<DocumentSummary> documents = new ArrayList<>();
            while (rs.next()) {
                documents.add(new DocumentSummary(
                        rs.getString("document_id"), rs.getString("title"), rs.getString("template_name"),
                        rs.getString("status"), rs.getString("created_at")));
            }
            return documents;
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }

    public List<SealSummary> listSealsForDocument(String documentId) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT seal_id, provider_id, key_alias, signature_standard, " +
                    "sealed_at::text AS sealed_at FROM document_seals WHERE document_id = ?::uuid ORDER BY sealed_at");
            ps.setString(1, documentId);
            rs = ps.executeQuery();
            List<SealSummary> seals = new ArrayList<>();
            while (rs.next()) {
                seals.add(new SealSummary(
                        rs.getString("seal_id"), rs.getString("provider_id"), rs.getString("key_alias"),
                        rs.getString("signature_standard"), rs.getString("sealed_at")));
            }
            return seals;
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }
}
