package org.tsicoop.sign.service.v1;

import org.tsicoop.sign.framework.PoolDB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

public class DocumentRepository {

    public record DocumentRecord(
            String documentId,
            String appId,
            String templateId,
            String title,
            String storageProviderId,
            String originalStorageKey,
            String originalHash,
            String sealedStorageKey,
            String sealedHash,
            String status,
            String archivedAt
    ) {
    }

    public record DocumentSummary(
            String documentId, String title, String templateName, String status, String createdAt, String archivedAt
    ) {
    }

    public record SealSummary(
            String sealId, String providerId, String keyAlias, String signatureStandard, String sealedAt
    ) {
    }

    /**
     * documentId is generated by the caller (not left to the DB's default)
     * because the storage key (§5) is derived from it before the row is
     * ever written — the PDF must land at a path containing the same id
     * that ends up in documents.document_id.
     */
    public void createDraftWithId(String documentId, String appId, String templateId, String title,
                                   String storageProviderId, String originalStorageKey, String originalHash)
            throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("INSERT INTO documents " +
                    "(document_id, app_id, template_id, title, storage_provider_id, original_storage_key, original_hash, status) " +
                    "VALUES (?::uuid, ?::uuid, ?::uuid, ?, ?, ?, ?, 'DRAFT')");
            ps.setString(1, documentId);
            ps.setString(2, appId);
            ps.setString(3, templateId);
            ps.setString(4, title);
            ps.setString(5, storageProviderId);
            ps.setString(6, originalStorageKey);
            ps.setString(7, originalHash);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /** Scoped to appId so one App can never seal/read another's document (§8). */
    public Optional<DocumentRecord> findByIdForApp(String appId, String documentId) {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = null;
        try {
            pool = new PoolDB();
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT document_id, app_id, template_id, title, storage_provider_id, " +
                    "original_storage_key, original_hash, sealed_storage_key, sealed_hash, status, " +
                    "archived_at::text AS archived_at " +
                    "FROM documents WHERE document_id = ?::uuid AND app_id = ?::uuid");
            ps.setString(1, documentId);
            ps.setString(2, appId);
            rs = ps.executeQuery();
            if (rs.next()) {
                return Optional.of(new DocumentRecord(
                        rs.getString("document_id"),
                        rs.getString("app_id"),
                        rs.getString("template_id"),
                        rs.getString("title"),
                        rs.getString("storage_provider_id"),
                        rs.getString("original_storage_key"),
                        rs.getString("original_hash"),
                        rs.getString("sealed_storage_key"),
                        rs.getString("sealed_hash"),
                        rs.getString("status"),
                        rs.getString("archived_at")));
            }
            return Optional.empty();
        } catch (Exception e) {
            return Optional.empty();
        } finally {
            if (pool != null) pool.cleanup(rs, ps, con);
        }
    }

    /**
     * Unscoped by appId - only used from the eSign callback path (§ Aadhaar
     * eSign plan), which has no caller-supplied appId to scope by. Safe
     * there because that path only ever reaches a documentId via an
     * esign_sessions row keyed by a UUID transaction_id known only to the
     * legitimate in-flight session, not via untrusted caller input.
     */
    public Optional<DocumentRecord> findById(String documentId) {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = null;
        try {
            pool = new PoolDB();
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT document_id, app_id, template_id, title, storage_provider_id, " +
                    "original_storage_key, original_hash, sealed_storage_key, sealed_hash, status, " +
                    "archived_at::text AS archived_at " +
                    "FROM documents WHERE document_id = ?::uuid");
            ps.setString(1, documentId);
            rs = ps.executeQuery();
            if (rs.next()) {
                return Optional.of(new DocumentRecord(
                        rs.getString("document_id"),
                        rs.getString("app_id"),
                        rs.getString("template_id"),
                        rs.getString("title"),
                        rs.getString("storage_provider_id"),
                        rs.getString("original_storage_key"),
                        rs.getString("original_hash"),
                        rs.getString("sealed_storage_key"),
                        rs.getString("sealed_hash"),
                        rs.getString("status"),
                        rs.getString("archived_at")));
            }
            return Optional.empty();
        } catch (Exception e) {
            return Optional.empty();
        } finally {
            if (pool != null) pool.cleanup(rs, ps, con);
        }
    }

    public void markPending(String documentId) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET status = 'PENDING', updated_at = now() " +
                    "WHERE document_id = ?::uuid");
            ps.setString(1, documentId);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    public void markExpired(String documentId) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET status = 'EXPIRED', updated_at = now() " +
                    "WHERE document_id = ?::uuid");
            ps.setString(1, documentId);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /**
     * Reverts a PENDING document after a failed/denied eSign attempt, so it
     * can be retried - DRAFT if no signer has completed yet, or
     * PARTIALLY_SIGNED if this was one signer's turn on an otherwise
     * multi-signature document (docs/architecture.md §6.4).
     */
    public void markStatus(String documentId, String status) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET status = ?, updated_at = now() WHERE document_id = ?::uuid");
            ps.setString(1, status);
            ps.setString(2, documentId);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /**
     * Optimistic-concurrency seal write (docs/architecture.md §6.4
     * §5): only applies if sealed_hash still matches what the caller read
     * immediately before sealing - two signers racing to seal at once means
     * the second write fails cleanly (returns false) instead of silently
     * clobbering the first signer's work. status is parameterized
     * (PARTIALLY_SIGNED vs SIGNED) rather than hardcoded, since a document
     * with outstanding signers isn't fully executed yet.
     */
    public boolean markSealedIfHashMatches(String documentId, String sealedStorageKey, String sealedHash,
                                            String expectedPreviousSealedHash, String newStatus) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET sealed_storage_key = ?, sealed_hash = ?, " +
                    "status = ?, updated_at = now() WHERE document_id = ?::uuid AND sealed_hash IS NOT DISTINCT FROM ?");
            ps.setString(1, sealedStorageKey);
            ps.setString(2, sealedHash);
            ps.setString(3, newStatus);
            ps.setString(4, documentId);
            ps.setString(5, expectedPreviousSealedHash);
            return ps.executeUpdate() > 0;
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /**
     * Archiving is independent of signing-lifecycle status (§ documents.status)
     * - a SIGNED document stays SIGNED once archived, it's just hidden from
     * the default Documents list and frozen against further seal/eSign
     * activity until unarchived. Scoped to appId for tenant isolation;
     * returns false if no row matched, so the caller can 404.
     */
    public boolean archive(String appId, String documentId) throws Exception {
        return setArchived(appId, documentId, true);
    }

    public boolean unarchive(String appId, String documentId) throws Exception {
        return setArchived(appId, documentId, false);
    }

    private boolean setArchived(String appId, String documentId, boolean archived) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("UPDATE documents SET archived_at = " + (archived ? "now()" : "NULL") +
                    ", updated_at = now() WHERE document_id = ?::uuid AND app_id = ?::uuid");
            ps.setString(1, documentId);
            ps.setString(2, appId);
            return ps.executeUpdate() > 0;
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    public void insertSeal(String documentId, String signerId, String providerId, String keyAlias,
                            String transactionId, String pkcs7Signature, String signatureStandard,
                            String caIssuer, String authType) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("INSERT INTO document_seals " +
                    "(document_id, signer_id, provider_id, key_alias, transaction_id, pkcs7_signature, " +
                    "signature_standard, ca_issuer, auth_type) " +
                    "VALUES (?::uuid, ?::uuid, ?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, documentId);
            ps.setString(2, signerId);
            ps.setString(3, providerId);
            ps.setString(4, keyAlias);
            ps.setString(5, transactionId);
            ps.setString(6, pkcs7Signature);
            ps.setString(7, signatureStandard);
            ps.setString(8, caIssuer);
            ps.setString(9, authType);
            ps.executeUpdate();
        } finally {
            pool.cleanup(null, ps, con);
        }
    }

    /**
     * §10.4 Documents & Audit Trail list, scoped to one App, paginated and
     * optionally search-filtered. Archived documents are excluded by
     * default - the console's normal list is meant to stay uncluttered by
     * what's been put away; includeArchived powers an explicit "show
     * archived" view instead. search does a case-insensitive ILIKE match
     * against the document title, matching tsi-compass's list_controls
     * search convention (no full-text tsvector index - not warranted at
     * this scale, and not how any sibling TSI product does it either).
     */
    public List<DocumentSummary> listForApp(String appId, boolean includeArchived, String search,
                                             int page, int pageSize) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            String sql = "SELECT d.document_id, d.title, t.template_name, d.status, " +
                    "d.created_at::text AS created_at, d.archived_at::text AS archived_at FROM documents d " +
                    "LEFT JOIN templates t ON t.template_id = d.template_id " +
                    "WHERE d.app_id = ?::uuid" + (includeArchived ? "" : " AND d.archived_at IS NULL") +
                    (search != null && !search.isBlank() ? " AND d.title ILIKE ?" : "") +
                    " ORDER BY d.created_at DESC LIMIT ? OFFSET ?";
            ps = con.prepareStatement(sql);
            int i = 1;
            ps.setString(i++, appId);
            if (search != null && !search.isBlank()) {
                ps.setString(i++, "%" + search + "%");
            }
            ps.setInt(i++, pageSize);
            ps.setLong(i, (long) (page - 1) * pageSize);
            rs = ps.executeQuery();
            List<DocumentSummary> documents = new ArrayList<>();
            while (rs.next()) {
                documents.add(new DocumentSummary(
                        rs.getString("document_id"), rs.getString("title"), rs.getString("template_name"),
                        rs.getString("status"), rs.getString("created_at"), rs.getString("archived_at")));
            }
            return documents;
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }

    public int countForApp(String appId, boolean includeArchived, String search) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            String sql = "SELECT COUNT(*) FROM documents d WHERE d.app_id = ?::uuid" +
                    (includeArchived ? "" : " AND d.archived_at IS NULL") +
                    (search != null && !search.isBlank() ? " AND d.title ILIKE ?" : "");
            ps = con.prepareStatement(sql);
            int i = 1;
            ps.setString(i++, appId);
            if (search != null && !search.isBlank()) {
                ps.setString(i, "%" + search + "%");
            }
            rs = ps.executeQuery();
            rs.next();
            return rs.getInt(1);
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }

    /**
     * Dashboard aggregate (§10.1): document count matching any of the given
     * statuses, across every App the caller can see - null appIds means
     * every App (PLATFORM_ADMIN/AUDITOR); a concrete set scopes to an
     * APP_MANAGER's assigned Apps.
     */
    public int countForApps(Set<String> appIds, List<String> statuses) throws Exception {
        if (appIds != null && appIds.isEmpty()) return 0;
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM documents WHERE status IN (")
                    .append(placeholders(statuses.size(), "?")).append(")");
            if (appIds != null) {
                sql.append(" AND app_id IN (").append(placeholders(appIds.size(), "?::uuid")).append(")");
            }
            ps = con.prepareStatement(sql.toString());
            int i = 1;
            for (String status : statuses) {
                ps.setString(i++, status);
            }
            if (appIds != null) {
                for (String appId : appIds) {
                    ps.setString(i++, appId);
                }
            }
            rs = ps.executeQuery();
            rs.next();
            return rs.getInt(1);
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }

    private static String placeholders(int count, String token) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < count; i++) {
            if (i > 0) sb.append(",");
            sb.append(token);
        }
        return sb.toString();
    }

    public List<SealSummary> listSealsForDocument(String documentId) throws Exception {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        PoolDB pool = new PoolDB();
        try {
            con = pool.getConnection();
            ps = con.prepareStatement("SELECT seal_id, provider_id, key_alias, signature_standard, " +
                    "sealed_at::text AS sealed_at FROM document_seals WHERE document_id = ?::uuid ORDER BY sealed_at");
            ps.setString(1, documentId);
            rs = ps.executeQuery();
            List<SealSummary> seals = new ArrayList<>();
            while (rs.next()) {
                seals.add(new SealSummary(
                        rs.getString("seal_id"), rs.getString("provider_id"), rs.getString("key_alias"),
                        rs.getString("signature_standard"), rs.getString("sealed_at")));
            }
            return seals;
        } finally {
            pool.cleanup(rs, ps, con);
        }
    }
}
